### ISSUE TITLE
Builtin Main & Child thread

### ISSUE THREAD

**Issue by robertrinh** [robertrinh/minishell#101]
f.e.

qtrinh@f0r2s7:~/Documents/Github/Rank3/minishell$ `cat README.md | exit`
should not print exit

qtrinh@f0r2s7:~/Documents/Github/Rank3/minishell$ `cat README.md | exit @`
bash: exit: @: numeric argument required

still gives error

**Comment by QBeukelman** [comment]
`env | export 1`
`env | exit`

**Comment by QBeukelman** [comment]
`export 1=1`
