### ISSUE TITLE
Multiple processes bug

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#53]
Type the command `cat | cat | wc`. ^C should kill each process in order

**Comment by robertrinh** [comment]
Followup bug with signals / export:
Export seems to add new processes to the shell? When there is no export cases and when you press Ctrl-D, the minishell exits correctly. When exporting, apparantly it set up a new process and exits that one first, before it exits the main program?

<img width="693" alt="Screenshot 2024-03-15 at 17 07 01" src="https://github.com/robertrinh/minishell/assets/57951795/b9153ce5-84cc-469d-9b1b-dc99c8ea5e93">

**Comment by robertrinh** [comment]
command that i got from a peer

sleep 2 | cat /dev/urandom | head -c 100

it should run all at the same time and sleep would get triggered at the last. urandom is infinite garbage and head -c 100 takes up to a 100 chars and stops after the 100th char

**Comment by robertrinh** [comment]
adding a e'''''cho' hello does not entirely kill the process:

`[minishell]: c'''''at' README.md `
[minishell]: 
`
`[minishell]:`
