### ISSUE TITLE
Add support for expander 

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#56]
Expand env variables in quotes

"hello $USER" -> hello quentin

**Comment by QBeukelman** [comment]
Quotes on cmd

**Comment by QBeukelman** [comment]
export overwrite $TERM/last one?
_=Value

**Comment by QBeukelman** [comment]
$?

**Comment by QBeukelman** [comment]
`[minishell]: echo "hello "$USER"$COLORTERM more"
hello  truecolor more" `

second quote does not get registered ($USER)

**Comment by QBeukelman** [comment]
`e'ch'o hello` -> hello

**Comment by QBeukelman** [comment]
echo hello "my name is $USER and I use $TERM" <- ERROR

**Comment by robertrinh** [comment]
c'a'""t README.md <- no output
<img width="253" alt="Screenshot 2024-04-04 at 16 16 25" src="https://github.com/robertrinh/minishell/assets/57951795/ee16ae03-77d5-4c12-89ef-de13caf88de6">

**Comment by QBeukelman** [comment]
export 1=a -> not a valid identifier.

**Comment by QBeukelman** [comment]
export var="  truc" - echo $var | cat -e
