### ISSUE TITLE
Add support for Exit_Codes Heredoc

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#57]
* Manage exit codes of last operation.
* Write exit code with $?

**Comment by QBeukelman** [comment]
cat -> ctrl+c = 130, but gives 0

**Comment by robertrinh** [comment]
signals in heredoc not functional entirely exit_code wise.
grep aa<<EOF + ctrl+c = 130, gives 1

**Comment by QBeukelman** [comment]
Signal for heredoc in pipeline

**Comment by QBeukelman** [comment]
[minishell]: grep aa << EOF 
> 
[minishell]: [minishell]:
