### ISSUE TITLE
Add support for `show_error_message()`

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#72]
We have the method, `exit_with_error()`. But this exits the program.

We need the same functionality, but without exiting the program.

**Comment by QBeukelman** [comment]
export 1=a -> not a valid identifier.

**Comment by QBeukelman** [comment]
double pipes ||

**Comment by QBeukelman** [comment]
export with no options = error?

**Comment by QBeukelman** [comment]
A single command e.g. hello should execute, and show error message, command not found.

**Comment by QBeukelman** [comment]
echo "bip | bip ; coyotte > < "
should echo., but show error unmatched redirect

**Comment by QBeukelman** [comment]
Add support for exit code with corresponding error message

**Comment by robertrinh** [comment]
no such file or directory with error code 127 -> when unsetting PATH f.e.
