### ISSUE TITLE
Builtin: `cd`

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#73]
- Add support for `cd` builtin.
- Remove `jump table`, and find neat alternative.

**Comment by robertrinh** [comment]
`qtrinh@f1r5s15:~/Documents/Github/Rank3/minishell$ cd ..`
`qtrinh@f1r5s15:~/Documents/Github/Rank3$ cd -`
/home/qtrinh/Documents/Github/Rank3/minishell


`cd -` should input the old_pwd

**Comment by robertrinh** [comment]
Optimise cd (segfaults after using multiple unset/env)
