### ISSUE TITLE
copied env(shell->envp) might not work

### ISSUE THREAD

**Issue by robertrinh** [robertrinh/minishell#74]
There seems to be a bit of trouble using our shell->envp. 
I modified the ft_getenv to get any value in the copied shell instead of just path, and tried to understand the function chdir: a quick check gave me the following:

Using our own ft_getenv (thus shell->envp)
`[minishell]: cd
getenv from copied env gives: home/qtrinh/Documents/Github/Rank3/minishell
chdir failed
global exit code after executing is -1
[minishell]: 
exit
global exit code after executing is 0
[minishell]: 
exit`

Using getenv (which uses the original env)
`[minishell]: cd
getenv from original source gives: /home/qtrinh/Documents/Github/Rank3/minishell
chdir worked!
global exit code after executing is 73
[minishell]: 
exit
global exit code after executing is 0
[minishell]: 
exit`

**Comment by QBeukelman** [comment]
It looks line the diff is in the relative/non-relative paths. ie `/home` vs `home`.

Would you be able to append the `/` to the path of our own env?

**Comment by robertrinh** [comment]
resolved issue by doing a different method ;)
