### ISSUE TITLE
Reset shell

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#85]

**Comment by robertrinh** [comment]
There are multiple ''processes'' when we finish a command. Think it has to do with not resetting values?

<img width="496" alt="Screenshot 2024-04-17 at 17 19 54" src="https://github.com/robertrinh/minishell/assets/57951795/658bde15-3384-4f27-8c97-0218bd9e74ea">

**Comment by robertrinh** [comment]
my guessed issue is that the cmd_table is not properly reset, as it would still hold value of ls when we do a second run.

minishell: ls
includes  Makefile  minishell  obj  README.md  sources  tests
minishell: (SPACEBAR INPUT)
includes  Makefile  minishell  obj  README.md  sources  tests

**Comment by robertrinh** [comment]
double pipe segfault after inputting a valid command?

minishell (double pipe) cat README.md ||
minishell: invalid operator.
[minishell]: cat README.md | grep aa ||
minishell: invalid operator.
[minishell]: cat README.md | grep aa
aa
aa
aa
[minishell]: cat README.md | grep aa ||
minishell: invalid operator.
[1]    230847 segmentation fault (core dumped)  ./minishell

**Comment by robertrinh** [comment]
free split struct after succesful split

**Comment by robertrinh** [comment]
free parser struct

**Comment by robertrinh** [comment]
free infiles struct + ins->heredoc + ins->infiles
