### ISSUE TITLE
Global variables for jump table and error messages

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#87]
- Add norm friendly method for builtin function jump table.
- Add norm friendly method for error messages.

**Comment by robertrinh** [comment]
question:
I'm trying to restructure some code according to the compilation flags. In the builtins, not all builtins use the shell struct (f.e. pwd doesn't use any struct at all). For the jump table, is it necessary that all the functions require the same params? if so, then I suggest we should walk away from the jump table, as that would not be possible :(

An example:
<img width="654" alt="Screenshot 2024-04-11 at 18 13 53" src="https://github.com/robertrinh/minishell/assets/57951795/dd2b1efd-c9c3-4235-a6d0-d741494c0f3f">
