### ISSUE TITLE
Norminette

### ISSUE THREAD

**Issue by robertrinh** [robertrinh/minishell#94]

**Comment by QBeukelman** [comment]
Shorten Split

**Comment by robertrinh** [comment]
allocate_strings_split

**Comment by robertrinh** [comment]
shorten tokenize_command + assign_lexer_types

**Comment by robertrinh** [comment]
Error: MISALIGNED_VAR_DECL  (line: 172, col:   1):      Misaligned variable declaration

-> forward declaration of `builtin struct`
